export interface Adoption{
    id: string,
    uid: string,
    title:string,
    pets_number: number,
    pets: string[],
    description: string,
    needs: string,
    img: string,
    location: string,
    lat: number,
    lng: number,
    report_state: string,
    creation_date: string,
}