export interface Pet{
    id: string,
    uid: string,
    specie: string,
    breed: string,
    animal_gender: number,
    names: string,
    photo: string,
    weight: number,
    height: number,
    size: number,
    birthday: string,
    age: number,
    pet_age: number,
    has_adopted_here: boolean,
    isForAdoption: boolean,
    isLost: boolean,
    color: string,
    medical_info: string,
    vaccine_info: string,
    chip_id: string,
    registration_date: string,
}
