export interface User{
    uid: string,
    names: string,
    profile_img: string,
    birthday: string,
    age: number,
    gender: string,
    phone: number,
    email: string,
    username: string,
    password: string,
    pets_number: number,
    pets: string[],
    has_vet: boolean,
    has_store: boolean,
    pet_foster: boolean,
    address: string,
    comuna: string,
    region: string,
    lat: number,
    lng: number,
    notifications: boolean,
    creation_date: string,
    last_login: string,
}
